import { Tag } from "react-tag-input";

const suggestions: Tag[] = [
  { id: "Developer", text: "Developer" },
  { id: "React", text: "React" },
  { id: "Tailwind", text: "Tailwind" },
  { id: "Nextjs", text: "Nextjs" },
  { id: "Hello-World", text: "Hello-World" },
  { id: "JavaScript", text: "JavaScript" },
  { id: "TypeScript", text: "TypeScript" },
  { id: "Node.js", text: "Node.js" },
  { id: "Express.js", text: "Express.js" },
  { id: "Vue.js", text: "Vue.js" },
  { id: "Angular", text: "Angular" },
  { id: "GraphQL", text: "GraphQL" },
  { id: "REST API", text: "REST API" },
  { id: "MongoDB", text: "MongoDB" },
  { id: "MySQL", text: "MySQL" },
  { id: "Python", text: "Python" },
  { id: "Django", text: "Django" },
  { id: "Flask", text: "Flask" },
  { id: "Machine Learning", text: "Machine Learning" },
  { id: "Data Science", text: "Data Science" },
  { id: "TensorFlow", text: "TensorFlow" },
  { id: "PyTorch", text: "PyTorch" },
  { id: "Java", text: "Java" },
  { id: "Spring Boot", text: "Spring Boot" },
  { id: "Kotlin", text: "Kotlin" },
  { id: "HTML", text: "HTML" },
  { id: "CSS", text: "CSS" },
  { id: "Sass", text: "Sass" },
  { id: "Bootstrap", text: "Bootstrap" },
  { id: "UI Design", text: "UI Design" },
  { id: "UX Design", text: "UX Design" },
  { id: "Responsive Design", text: "Responsive Design" },
  { id: "Adobe Photoshop", text: "Adobe Photoshop" },
  { id: "Adobe Illustrator", text: "Adobe Illustrator" },
  { id: "Git", text: "Git" },
];
export default suggestions;
